channels:
- conda-forge
dependencies:
- python=3.12.12
- pip<=25.3
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.1.2
  - scikit-learn==1.3.2
  - scipy==1.16.3
name: mlflow-env
